In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
os.getcwd()
os.chdir('/content/drive/MyDrive')
crops = pd.read_csv('faostat_crops.csv', encoding= 'cp1252')
crops

<ipython-input-6-38c8bfa23c5f>:3: DtypeWarning: Columns (11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92,95,98,101,104,107,110,113,116,119,122,125,128,131,134,137,140,143,146,149,152,155,158,161,164,167,170,173,176,179,182,185,188,191) have mixed types. Specify dtype option on import or set low_memory=False.
  crops = pd.read_csv('faostat_crops.csv', encoding= 'cp1252')

,Area Code,Area Code (M49),Area,Item Code,Item Code (CPC),Item,Element Code,Element,Unit,Y1961,...,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N,Y2021,Y2021F,Y2021N
0,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5312,Area harvested,ha,NaN,...,NaN,29203.00,A,NaN,22134.00,A,NaN,21685.00,I,NaN
1,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5419,Yield,100 g/ha,NaN,...,NaN,13083.00,A,NaN,17759.00,A,NaN,18748.00,E,NaN
2,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5510,Production,t,NaN,...,NaN,38205.00,A,NaN,39307.00,A,NaN,40655.23,I,NaN
3,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5312,Area harvested,ha,NaN,...,NaN,27387.00,I,NaN,26255.00,E,NaN,26287.00,E,NaN
4,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5419,Yield,100 g/ha,NaN,...,NaN,6902.00,E,NaN,7409.00,E,NaN,7379.00,E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79292,5817,'902,Net Food Importing Developing Countries,1729,'F1729,"Treenuts, Total",5419,Yield,100 g/ha,6118.0,...,NaN,5346.00,E,NaN,5426.00,E,NaN,5515.00,E,NaN
79293,5817,'902,Net Food Importing Developing Countries,1729,'F1729,"Treenuts, Total",5510,Production,t,255724.0,...,NaN,2314274.21,E,NaN,2479586.92,E,NaN,2498539.75,E,NaN
79294,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5312,Area harvested,ha,1877800.0,...,NaN,7543355.00,E,NaN,7710160.00,E,NaN,7978161.00,E,NaN
79295,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5419,Yield,100 g/ha,66297.0,...,NaN,117830.00,E,NaN,117831.00,E,NaN,117360.00,E,NaN
79296,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5510,Production,t,12449173.0,...,NaN,88883639.40,E,NaN,90849506.59,E,NaN,93631442.78,E,NaN

In [7]:
crops.dtypes

Area Code            int64
Area Code (M49)     object
Area                object
Item Code            int64
Item Code (CPC)     object
                    ...
Y2020F              object
Y2020N              object
Y2021              float64
Y2021F              object
Y2021N              object
Length: 192, dtype: object

In [13]:
data_cleaned = crops.dropna()

cleaned_file_path = "/content/drive/My Drive/cleaned_faostat_crops.csv"
data_cleaned.to_csv(cleaned_file_path, index=False)

print("\nCleaned Data:")
print(data_cleaned.head())

Cleaned Data:
    Area Code Area Code (M49)         Area  Item Code Item Code (CPC)  \
6           2            '004  Afghanistan        515          '01341
7           2            '004  Afghanistan        515          '01341
8           2            '004  Afghanistan        515          '01341
9           2            '004  Afghanistan        526          '01343
10          2            '004  Afghanistan        526          '01343

        Item  Element Code         Element      Unit    Y1961  ...     Y2012  \
6     Apples          5312  Area harvested        ha   2220.0  ...    9148.0
7     Apples          5419           Yield  100 g/ha  68018.0  ...   76519.0
8     Apples          5510      Production         t  15100.0  ...   70000.0
9   Apricots          5312  Area harvested        ha   4820.0  ...    8350.0
10  Apricots          5419           Yield  100 g/ha  66390.0  ...  100000.0

      Y2013    Y2014    Y2015     Y2016     Y2017     Y2018     Y2019  \
6   10341.0  12247.0  13038.0   19365.0   26847.0   28381.0   27559.0
7   76005.0  73000.0  68824.0   72762.0   63487.0   76527.0   90832.0
8   78597.0  89403.0  89733.0  140903.0  170443.0  217192.0  250324.0
9    9005.0   9005.0   9116.0    8595.0   18067.0   18510.0   17719.0
10  99944.0  99944.0  96189.0   20819.0   72960.0   58934.0   73008.0

       Y2020      Y2021
6    25643.0   26540.00
7   105626.0  110245.00
8   270857.0  292586.58
9    17481.0   15199.00
10   75389.0   74779.00

[5 rows x 70 columns]

In [ ]:
#Cleaning the crops data set so that only only the observations with element = area harvested or production remain
cropsDf.head()
mask = (cropsDf['Element'] == 'Area harvested') | (cropsDf['Element'] =='Production')
cropsDf = cropsDf[mask]
cropsDf = cropsDf.drop(['Area Code', 'Area Code (M49)', 'Item Code', 'Item Code (CPC)', 'Element Code'], axis = 1)
print(cropsDf['Area'].unique())
cropsDf.head()

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Antigua and Barbuda'
 'Argentina' 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium'
 'Belgium-Luxembourg' 'Belize' 'Benin' 'Bhutan'
 'Bolivia (Plurinational State of)' 'Bosnia and Herzegovina' 'Botswana'
 'Brazil' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'China, Hong Kong SAR' 'China, Macao SAR'
 'China, mainland' 'China, Taiwan Province of' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' "Côte d'Ivoire" 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Czechoslovakia'
 "Democratic People's Republic of Korea"
 'Democratic Republic of the Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Ethiopia PDR' 'Faroe Islands'
 'Fiji' 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon'
 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada' 'Guadeloupe'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran (Islamic Republic of)'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan'
 "Lao People's Democratic Republic" 'Latvia' 'Lebanon' 'Lesotho' 'Liberia'
 'Libya' 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique' 'Mauritania'
 'Mauritius' 'Mexico' 'Micronesia (Federated States of)' 'Mongolia'
 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'Netherlands (Kingdom of the)' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'Niue' 'North Macedonia' 'Norway' 'Oman' 'Pakistan'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Republic of Korea'
 'Republic of Moldova' 'Réunion' 'Romania' 'Russian Federation' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Serbia and Montenegro' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa'
 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Sudan (former)' 'Suriname'
 'Sweden' 'Switzerland' 'Syrian Arab Republic' 'Tajikistan' 'Thailand'
 'Timor-Leste' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Türkiye' 'Turkmenistan' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates'
 'United Kingdom of Great Britain and Northern Ireland'
 'United Republic of Tanzania' 'United States of America' 'Uruguay' 'USSR'
 'Uzbekistan' 'Vanuatu' 'Venezuela (Bolivarian Republic of)' 'Viet Nam'
 'Yemen' 'Yugoslav SFR' 'Zambia' 'Zimbabwe' 'World' 'Africa'
 'Eastern Africa' 'Middle Africa' 'Northern Africa' 'Southern Africa'
 'Western Africa' 'Americas' 'Northern America' 'Central America'
 'Caribbean' 'South America' 'Asia' 'Central Asia' 'Eastern Asia'
 'Southern Asia' 'South-eastern Asia' 'Western Asia' 'Europe'
 'Eastern Europe' 'Northern Europe' 'Southern Europe' 'Western Europe'
 'Oceania' 'Australia and New Zealand' 'Melanesia' 'Micronesia'
 'Polynesia' 'European Union (27)' 'Least Developed Countries'
 'Land Locked Developing Countries' 'Small Island Developing States'
 'Low Income Food Deficit Countries'
 'Net Food Importing Developing Countries']

,Area,Item,Element,Unit,Y1961,Y1961F,Y1961N,Y1962,Y1962F,Y1962N,...,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N,Y2021,Y2021F,Y2021N
0,Afghanistan,"Almonds, in shell",Area harvested,ha,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,29203.00,A,NaN,22134.0,A,NaN,21685.00,I,NaN
2,Afghanistan,"Almonds, in shell",Production,t,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,38205.00,A,NaN,39307.0,A,NaN,40655.23,I,NaN
3,Afghanistan,"Anise, badian, coriander, cumin, caraway, fenn...",Area harvested,ha,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,27387.00,I,NaN,26255.0,E,NaN,26287.00,E,NaN
5,Afghanistan,"Anise, badian, coriander, cumin, caraway, fenn...",Production,t,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18903.37,I,NaN,19453.5,I,NaN,19398.07,E,NaN
6,Afghanistan,Apples,Area harvested,ha,2220.0,E,NaN,2220.0,E,NaN,...,NaN,27559.00,A,NaN,25643.0,A,NaN,26540.00,I,NaN

In [8]:
dropColF = [col for col in cropsDf.columns if 'F' in col]
dropColN  = [col for col in cropsDf.columns if 'N' in col]
print(dropColF)
print(dropColN)

['Y1961F', 'Y1962F', 'Y1963F', 'Y1964F', 'Y1965F', 'Y1966F', 'Y1967F', 'Y1968F', 'Y1969F', 'Y1970F', 'Y1971F', 'Y1972F', 'Y1973F', 'Y1974F', 'Y1975F', 'Y1976F', 'Y1977F', 'Y1978F', 'Y1979F', 'Y1980F', 'Y1981F', 'Y1982F', 'Y1983F', 'Y1984F', 'Y1985F', 'Y1986F', 'Y1987F', 'Y1988F', 'Y1989F', 'Y1990F', 'Y1991F', 'Y1992F', 'Y1993F', 'Y1994F', 'Y1995F', 'Y1996F', 'Y1997F', 'Y1998F', 'Y1999F', 'Y2000F', 'Y2001F', 'Y2002F', 'Y2003F', 'Y2004F', 'Y2005F', 'Y2006F', 'Y2007F', 'Y2008F', 'Y2009F', 'Y2010F', 'Y2011F', 'Y2012F', 'Y2013F', 'Y2014F', 'Y2015F', 'Y2016F', 'Y2017F', 'Y2018F', 'Y2019F', 'Y2020F', 'Y2021F']
['Y1961N', 'Y1962N', 'Y1963N', 'Y1964N', 'Y1965N', 'Y1966N', 'Y1967N', 'Y1968N', 'Y1969N', 'Y1970N', 'Y1971N', 'Y1972N', 'Y1973N', 'Y1974N', 'Y1975N', 'Y1976N', 'Y1977N', 'Y1978N', 'Y1979N', 'Y1980N', 'Y1981N', 'Y1982N', 'Y1983N', 'Y1984N', 'Y1985N', 'Y1986N', 'Y1987N', 'Y1988N', 'Y1989N', 'Y1990N', 'Y1991N', 'Y1992N', 'Y1993N', 'Y1994N', 'Y1995N', 'Y1996N', 'Y1997N', 'Y1998N', 'Y1999N', 'Y2000N', 'Y2001N', 'Y2002N', 'Y2003N', 'Y2004N', 'Y2005N', 'Y2006N', 'Y2007N', 'Y2008N', 'Y2009N', 'Y2010N', 'Y2011N', 'Y2012N', 'Y2013N', 'Y2014N', 'Y2015N', 'Y2016N', 'Y2017N', 'Y2018N', 'Y2019N', 'Y2020N', 'Y2021N']

In [10]:
#Needs to be cleaned up
yearCol = cropsDf.columns
print(yearCol)
yearCol = yearCol.drop('Area')
yearCol = yearCol.drop('Item')
yearCol = yearCol.drop('Element')
yearCol = yearCol.drop('Unit')
yearCol

Index(['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item Code (CPC)',
       'Item', 'Element Code', 'Element', 'Unit', 'Y1961',
       ...
       'Y2018N', 'Y2019', 'Y2019F', 'Y2019N', 'Y2020', 'Y2020F', 'Y2020N',
       'Y2021', 'Y2021F', 'Y2021N'],
      dtype='object', length=192)

Index(['Area Code', 'Area Code (M49)', 'Item Code', 'Item Code (CPC)',
       'Element Code', 'Y1961', 'Y1961F', 'Y1961N', 'Y1962', 'Y1962F',
       ...
       'Y2018N', 'Y2019', 'Y2019F', 'Y2019N', 'Y2020', 'Y2020F', 'Y2020N',
       'Y2021', 'Y2021F', 'Y2021N'],
      dtype='object', length=188)

In [18]:
crops

,Area Code,Area Code (M49),Area,Item Code,Item Code (CPC),Item,Element Code,Element,Unit,Y1961,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021
0,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5312,Area harvested,ha,NaN,...,13490.00,14114.00,13703.00,14676.00,19481.00,19793.00,20053.00,29203.00,22134.00,21685.00
1,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5419,Yield,100 g/ha,NaN,...,45960.00,29910.00,19996.00,16521.00,16859.00,13788.00,17161.00,13083.00,17759.00,18748.00
2,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5510,Production,t,NaN,...,62000.00,42215.00,27400.00,24246.00,32843.00,27291.00,34413.00,38205.00,39307.00,40655.23
3,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5312,Area harvested,ha,NaN,...,18500.00,18500.00,30000.00,25000.00,24500.00,26160.00,25220.00,27387.00,26255.00,26287.00
4,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5419,Yield,100 g/ha,NaN,...,6757.00,6757.00,7167.00,7200.00,7075.00,6970.00,7866.00,6902.00,7409.00,7379.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79292,5817,'902,Net Food Importing Developing Countries,1729,'F1729,"Treenuts, Total",5419,Yield,100 g/ha,6118.0,...,5384.00,5303.00,5318.00,5422.00,5744.00,5927.00,5338.00,5346.00,5426.00,5515.00
79293,5817,'902,Net Food Importing Developing Countries,1729,'F1729,"Treenuts, Total",5510,Production,t,255724.0,...,1648809.17,1810688.35,1877336.94,2189212.78,2022188.76,2299639.12,2495666.54,2314274.21,2479586.92,2498539.75
79294,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5312,Area harvested,ha,1877800.0,...,6574958.00,6695517.00,6957204.00,7286193.00,7228932.00,7217374.00,7429029.00,7543355.00,7710160.00,7978161.00
79295,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5419,Yield,100 g/ha,66297.0,...,115066.00,113789.00,115754.00,115312.00,115667.00,116623.00,116194.00,117830.00,117831.00,117360.00
79296,5817,'902,Net Food Importing Developing Countries,1735,'F1735,Vegetables Primary,5510,Production,t,12449173.0,...,75655410.81,76187906.76,80532247.13,84018273.77,83614537.01,84171473.81,86320503.75,88883639.40,90849506.59,93631442.78

In [21]:
#Tried grouping the data frame in a way that would show how crop harvest changes for each country over the years
arrays = [
    crops['Item'],
    crops['Area']
]
#element = namedtuple("Element")
index = pd.MultiIndex.from_arrays(arrays, names=('Crop', 'Country'))
cropsA = pd.DataFrame(cropsDf[yearCol], index = index)
cropsA

                                                                                            Area Code  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
...                                                                                               ...
Treenuts, Total                                    Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN
Vegetables Primary                                 Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN

                                                                                           Area Code (M49)  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
...                                                                                                    ...
Treenuts, Total                                    Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN
Vegetables Primary                                 Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN

                                                                                            Item Code  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                    NaN
                                                   Afghanistan                                    NaN
...                                                                                               ...
Treenuts, Total                                    Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN
Vegetables Primary                                 Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN
                                                   Net Food Importing Developing Countries        NaN

                                                                                           Item Code (CPC)  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                         NaN
                                                   Afghanistan                                         NaN
...                                                                                                    ...
Treenuts, Total                                    Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN
Vegetables Primary                                 Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN
                                                   Net Food Importing Developing Countries             NaN

                                                                                            Element Code  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                       NaN
                                                   Afghanistan                                       NaN
                                                   Afghanistan                                       NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                       NaN
                                                   Afghanistan                                       NaN
...                                                                                                  ...
Treenuts, Total                                    Net Food Importing Developing Countries           NaN
                                                   Net Food Importing Developing Countries           NaN
Vegetables Primary                                 Net Food Importing Developing Countries           NaN
                                                   Net Food Importing Developing Countries           NaN
                                                   Net Food Importing Developing Countries           NaN

                                                                                            Y1961  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                           Y1961F  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                           Y1961N  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                            Y1962  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                           Y1962F  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                            ...  \
Crop                                               Country                                  ...
Almonds, in shell                                  Afghanistan                              ...
                                                   Afghanistan                              ...
                                                   Afghanistan                              ...
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                              ...
                                                   Afghanistan                              ...
...                                                                                         ...
Treenuts, Total                                    Net Food Importing Developing Countries  ...
                                                   Net Food Importing Developing Countries  ...
Vegetables Primary                                 Net Food Importing Developing Countries  ...
                                                   Net Food Importing Developing Countries  ...
                                                   Net Food Importing Developing Countries  ...

                                                                                           Y2018N  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                            Y2019  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                           Y2019F  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                           Y2019N  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
Vegetables Primary                                 Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

                                                                                            Y2020  \
Crop                                               Country
Almonds, in shell                                  Afghanistan                                NaN
                                                   Afghanistan                                NaN
                                                   Afghanistan                                NaN
Anise, badian, coriander, cumin, caraway, fenne... Afghanistan                                NaN
                                                   Afghanistan                                NaN
...                                                                                           ...
Treenuts, Total                                    Net Food Importing Developing Countries    NaN
                                                   Net Food Importing Developing Countries    NaN

In [22]:
cropsB = crops.groupby(['Item'])
cropsB.head()

,Area Code,Area Code (M49),Area,Item Code,Item Code (CPC),Item,Element Code,Element,Unit,Y1961,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021
0,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5312,Area harvested,ha,NaN,...,13490.0,14114.0,13703.0,14676.0,19481.0,19793.0,20053.0,29203.00,22134.00,21685.00
1,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5419,Yield,100 g/ha,NaN,...,45960.0,29910.0,19996.0,16521.0,16859.0,13788.0,17161.0,13083.00,17759.00,18748.00
2,2,'004,Afghanistan,221,'01371,"Almonds, in shell",5510,Production,t,NaN,...,62000.0,42215.0,27400.0,24246.0,32843.0,27291.0,34413.0,38205.00,39307.00,40655.23
3,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5312,Area harvested,ha,NaN,...,18500.0,18500.0,30000.0,25000.0,24500.0,26160.0,25220.0,27387.00,26255.00,26287.00
4,2,'004,Afghanistan,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5419,Yield,100 g/ha,NaN,...,6757.0,6757.0,7167.0,7200.0,7075.0,6970.0,7866.0,6902.00,7409.00,7379.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67545,5207,'005,South America,1150,'02192.01,Other rodents,5112,Stocks,1000 An,20657.0,...,18925.0,18925.0,18925.0,18949.0,18953.0,18953.0,18954.0,19086.00,19132.00,19177.00
68047,5300,'142,Asia,778,'01929.03,"Kapok fibre, raw",5510,Production,t,65400.0,...,92455.0,89663.0,96000.0,95790.0,93240.0,91670.0,90520.0,78657.00,78674.00,NaN
68051,5300,'142,Asia,311,'01499.06,Kapokseed in shell,5510,Production,t,162464.4,...,205789.6,199474.3,197606.0,181011.0,171493.0,165766.0,160186.0,187502.59,187536.71,NaN
70304,5304,'035,South-eastern Asia,778,'01929.03,"Kapok fibre, raw",5510,Production,t,65400.0,...,92455.0,89663.0,96000.0,95790.0,93240.0,91670.0,90520.0,78657.00,78674.00,NaN
70308,5304,'035,South-eastern Asia,311,'01499.06,Kapokseed in shell,5510,Production,t,162464.4,...,205789.6,199474.3,197606.0,181011.0,171493.0,165766.0,160186.0,187502.59,187536.71,NaN

In [24]:
cropCnt = crops.drop('Area', axis = 1)
cropCnt = cropCnt[cropCnt['Element'] == 'Production']
cropCnt

,Area Code,Area Code (M49),Item Code,Item Code (CPC),Item,Element Code,Element,Unit,Y1961,Y1962,...,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021
2,2,'004,221,'01371,"Almonds, in shell",5510,Production,t,NaN,NaN,...,6.200000e+04,4.221500e+04,2.740000e+04,2.424600e+04,3.284300e+04,2.729100e+04,3.441300e+04,3.820500e+04,3.930700e+04,4.065523e+04
5,2,'004,711,'01654,"Anise, badian, coriander, cumin, caraway, fenn...",5510,Production,t,NaN,NaN,...,1.250000e+04,1.250000e+04,2.150000e+04,1.800000e+04,1.733333e+04,1.823412e+04,1.983733e+04,1.890337e+04,1.945350e+04,1.939807e+04
8,2,'004,515,'01341,Apples,5510,Production,t,15100.0,15100.0,...,7.000000e+04,7.859700e+04,8.940300e+04,8.973300e+04,1.409030e+05,1.704430e+05,2.171920e+05,2.503240e+05,2.708570e+05,2.925866e+05
11,2,'004,526,'01343,Apricots,5510,Production,t,32000.0,32000.0,...,8.350000e+04,9.000000e+04,9.000000e+04,8.768600e+04,1.789400e+04,1.318160e+05,1.090860e+05,1.293630e+05,1.317880e+05,1.136597e+05
15,2,'004,44,'0115,Barley,5510,Production,t,378000.0,378000.0,...,5.040000e+05,5.140000e+05,5.210000e+05,4.030000e+05,3.018560e+05,9.499500e+04,5.678100e+04,1.235760e+05,1.277570e+05,1.226928e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79284,5817,'902,1807,'F1807,Sheep and Goat Meat,5510,Production,t,953869.0,970039.0,...,3.148282e+06,3.223732e+06,3.306184e+06,3.473311e+06,3.484430e+06,3.670023e+06,3.731396e+06,3.887529e+06,4.140439e+06,4.078529e+06
79287,5817,'902,1809,'F1809,"Skim Milk & Buttermilk, Dry",5510,Production,t,1347.0,1347.0,...,1.182200e+04,1.416000e+04,4.261400e+04,4.377500e+04,4.544900e+04,4.498200e+04,5.912100e+04,6.020500e+04,6.154000e+04,NaN
79290,5817,'902,1723,'F1723,Sugar Crops Primary,5510,Production,t,121862378.0,106748036.0,...,2.076347e+08,2.256821e+08,2.271274e+08,2.298778e+08,2.363190e+08,2.433452e+08,2.229805e+08,2.275054e+08,2.364157e+08,2.440630e+08
79293,5817,'902,1729,'F1729,"Treenuts, Total",5510,Production,t,255724.0,295318.0,...,1.648809e+06,1.810688e+06,1.877337e+06,2.189213e+06,2.022189e+06,2.299639e+06,2.495667e+06,2.314274e+06,2.479587e+06,2.498540e+06
79296,5817,'902,1735,'F1735,Vegetables Primary,5510,Production,t,12449173.0,13016875.0,...,7.565541e+07,7.618791e+07,8.053225e+07,8.401827e+07,8.361454e+07,8.417147e+07,8.632050e+07,8.888364e+07,9.084951e+07,9.363144e+07